import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MainLayout from "../layouts/MainLayout";
import Wave from "../components/animations/Wave";
import {useDispatch, useSelector} from "react-redux";
import {RootState} from "../store";
import {useEffect} from "react";
import {getProducts} from "../store/storeSlice/productsSlice";
import * as React from "react";
import {GetStaticProps} from 'next'
import GetUser from '../components/product-table/GetUser';

export const getStaticProps = async () => {
    const response = await fetch('https://jsonplaceholder.typicode.com/users');
    const data = await response.json();

    return {
        props: {contacts: data},
    }
}



const Home = ({contacts}) => {
    // const {product, loading} = useSelector((state: RootState ) => state.products)
    // const dispatch = useDispatch()
    // useEffect(() => {
    //     // @ts-ignore
    //     dispatch(getProducts())
    // },[])
    // useEffect(() => {
    //         const getData = async () => {
    //             const response = await fetch(`http://rvi.17bit.online:31700/api/types?&json_indent=4&bytarget=unf_product_t&title=1`)
    //             const data = await response.json()
    //             JSON.stringify(data)
    //         }
    //         getData().then(r => r)
    //     }, [])
    //
    // if(loading) {
    //     return <h2>Loading</h2>
    // }

    // @ts-ignore
    return (
        <>
            <MainLayout>
                <Wave/>
                <Head>
                    <title>Settlement Service</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <table>
                        <tr>
                            <th className='topnav'>Users in API!!!</th>
                        </tr>
                        {contacts && contacts.map(({id, name, email}) => (
                            <tr>
                                <td>{id}</td>
                                <td>{name}</td>
                                <td>{email}</td>
                            </tr>
                        ))}
                    </table>
                </main>
                <footer className={styles.footer}>
                    Footer
                </footer>
            </MainLayout>
        </>
    )
}

export default Home;

// products: data.slice(0, 10),

