import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MainLayout from "../layouts/MainLayout";
import Wave from "../components/animations/Wave";


export default function Home() {

    return (
        <>
           <MainLayout>
              <Wave />
           </MainLayout>
            <div className={styles.container}>
                <Head>
                    <title>Settlement Service</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Welcome to <a href="https://nextjs.org">Next.js!</a>
                    </h1>
                </main>
                <footer className={styles.footer}>

                </footer>
            </div>
        </>
    )
}
